digitalfabrik/lunes-cms

- src/vocgui/static/scripts.js
This feature contains a new counter for the end results next to "falsch" and "richtig", namely "fast richtig" (almost correct). If the user types the right letters for the asked word, but makes a mistake by typing lower or higher case, it will be recognized as "fast richtig". The number of almost correct attempts will also be shown in the end results. It adds to the final result value like a correct attempt.
> Add "almost correct" counter, partially solves #5

- src/vocgui/static/scripts.js
- src/vocgui/static/style.css
Changes the functioning and appearance of the vocabulary questions.
- Instead of showing the user the two buttons "Solve" and "Next Word", show "Solve" and "Verify". 
- After triggering either of these buttons, the user is not able to change the input field anymore. Only now, the user is shown the "Next Word" button.
- The border of the input field is colored red, yellow, depending on if the input was wrong, almost wrong or correct.
- Separate function "next document" into two individual functions "load_new_document" and "check_current_document".
> Modify Button Setup, solves #18

- src/vocgui/static/scripts.js
Adds the option of starting a new round with only the not correct words after you finished a session.
- Button "Fehler üben" added. Triggering the button causes the start of a new round with only the _not_ correct words of the last round.
- Function _mistake_training_session()_ added to set the global variables to the correct values in order to only use wrong words in the session.
> Mistake round, solves #11

- src/vocgui/static/scripts.js
Adds a second try after you got something almost right. Moreover it provides the option to supply a hint together with that second try. It is also now checked if you made mistakes due to case sensitivity.
- By writing a new method: `render_almost_right(current_document, content_textfield, hint = "")`
- By adding an if clause to the `check_current_document()` function
- By adapting `verify_document()` and giving the `verificationObject` another attribute
> Improvement almost right feedback, solves #5

- src/voctrainer/settings.py
* Including the lines breaks production environment and it seems to work without.
> Settings: remove thumbnail

- README.md
- src/vocgui/serializers.py
- src/vocgui/views.py
**Issue:** 
- the frontend needs the number of training sets when calling `/api/disciplines/` for each discipline object
-  the frontend needs the number of documents when calling `api/training_set/[DISCIPLINE_ID]` for each training set_object
**Solution:**
- added `Count` annotation to the respective classes in `views.py`
- added the respective attribute to the corresponding serializers
> Feature/countmodules, fixes #74

- src/vocgui/forms.py
- src/vocgui/list_filter.py
- src/vocgui/models.py
- src/vocgui/validators.py
- src/voctrainer/settings.py
- upload of different audio formats should be possible
- audio files saved should be standardized 44.1khz mp3
- implemented automatic conversion to .mp3 44.1khz using pydub (partially used https://hvitis.dev/how-to-convert-audio-files-with-python-and-django)
- added validation for file size (max 5MB) and file format (.mp3 .aac .wav .m4a .wma .ogg)
- currently 3 files are saved per upload (original, converted, document audio (copy of converted))
> Feature/audio fixes #76

- src/locale/de/LC_MESSAGES/django.po
- src/locale/en/LC_MESSAGES/django.po
- src/locale/fr/LC_MESSAGES/django.po
- src/vocgui/admin.py
- src/vocgui/models.py
- models in django admin sidebar aren't in fixed order but sorted alphabetically
- overrode get_app_list function of AdminSite with custom ordering (1. discipline 2. training set 3. document)
- added try catch to prevent key error when trying to sort different app (e.g. Authentication and authorization) using custom ordering
- fixed displayed name of trainingset 
- fixed discipline verbose_name_plural
> Feature/ordered sidebar new fixes #105

- src/vocgui/admin.py
- src/voctrainer/settings.py
**Problems:**
- inline modules of `documents` tab was not user friendly
**Proposed Solutions**
- removed `nested-admin` package and deployed the django inline modules equivalent instead
- this removed the second header and improved the layout in general
> adapt inline modules fixes  #117

- README.md
- src/vocgui/admin.py
- src/vocgui/apps.py
- src/vocgui/forms.py
- src/vocgui/list_filter.py
- src/vocgui/models.py
- src/vocgui/serializers.py
- src/vocgui/urls.py
- src/vocgui/views.py
**Problems:**
It was not possible to manage different disciplines, training sets and documents according to multiple user groups.
**Proposed Changes:**
- Users only see the modules that belong to their group in django admin. If the user is superadmin, all elements will be displayed.
- added a group list_display element
- filtered the many to many selectors accordingly
- implemented a optional endpoint in order to fetch all disciplines of a specific group
- optional setting to provide a default user group
- adapted read me
- black formatting
> Feature/basic authentication fixes #140 #136 #137

- src/vocgui/admin.py
- There is no overview for vocabulary with missing files (audio/image)
- Added has_image and has_audio to document list display 
- Implemented ordering when clicking on audio/image/creatorgroup in vocabulary overview
> Feature/has_audio has_image list display

- src/vocgui/models.py
- src/voctrainer/settings.py
Solved issues:
- #133: custom icons for disciplines, training sets and documents by adapting the corresponding jazzmin settings
- #171: excluded `.tiff` files from image preview since they can not (easily) be displayed in an `image` node
> Custom icons, tiff support & improved public upload

- src/vocgui/models.py
- src/vocgui/utils.py
Make many to many selector of training set module searchable for alternative words.
- implemented custom function in `utils.py` that includes alternative words in string representation of a document
Fixes: #111
> add alt words to str representation of document

- src/vocgui/models.py
added resizing for images that are smaller than the final resolution
- resize the image to either width or height of final resolution (keep the ratio) depending on the width/height ratio of the image 
Fixes: #168
> Upscale images that are smaller than final resolution

- src/vocgui/admins/document_admin.py
When searching for an alternative word in the document list display, the user now can see corresponding documents that are linked to the respective alternative word.
- adapted search fields of `documents` admin file
Fixes: #215
> adapt search for alternative words fixes #215

- src/vocgui/views.py
When adding multiple images to a document, the word count will be displayed incorrectly. For Example, a training set containg 10 documents, 9 of them with only one image, but another one with two, will then result in the incorrect word count of 11.
- Adapt views.py so that only distinct documents are counted
Fixes: #224
> fix word count, fixes #224

- src/voctrainer/settings.py
This PR removes default authentication from `settings.py` since our endpoints are generally free to use and don't require login credentials. However, this seems to mess up our api key authentication system.
- remove respective variable in `settings.py`
> remove default auth classes from settings

- src/vocgui/urls.py
This might or might not fix some problems for the iOS app which can't handle redirects correctly.
Add an `OptionalSlashRouter` with an optional trailing slash
(Taken from https://stackoverflow.com/a/46163870)
> Enable optional trailing slash without redirect

- src/vocgui/admins/training_set_admin.py
- src/vocgui/models/training_set.py
Limit the description field to defined width, so the view does not break if long strings without spaces are entered
na
> fix: Break line in description field if word is too long

- src/vocgui/admins/group_api_key_admin.py
- src/vocgui/models/group_api_key.py
- src/vocgui/tests/test_utils.py
- src/vocgui/utils.py
This PR introduces a custom API-Key generator. It limits key length and excludes critical characters like 1, l or I.
-  create CustomKeyGenerator and include it in a custom GroupAPIKeyManager
-  helper function get_random_key that creates custom, but random strings 
Fixes: #268
> custom key generator fixes  #268

- src/vocgui/templates/public_upload.html
We do not want "Allgemeine Grundlagen" to show up in the public upload form.
Skip the element if the name is matched. This is a pretty dirty hack, but currently I do not see the need for a configurable list that can be changed in the back end.
> Public upload: skip Allgemeine Grundlagen

- src/vocgui/static/css/corporate_identity.css
- src/vocgui/static/css/overlay.css
- src/voctrainer/settings.py
When the user's browser is in dark mode, the "darkly" scheme will be used with a few custom modifications to keep the corporate identity design.
- Add "darkly" theme when browser is in dark mode
- Add a few custom background colors to match the general color scheme
Fixes: #298
> Add dark mode theme

- src/vocgui/admins/document_admin.py
- src/vocgui/admins/training_set_admin.py
- src/vocgui/list_filter.py
- src/vocgui/models/document.py
- src/vocgui/views/discipline_viewset.py
This PR implements a custom discipline filter for the training set list display. Along the way, I enabled user groups to add Lunes documents to their custom training sets and removed the `ApprovedImageListFilter` for user groups
- custom list filter since the `mptt tree filter` displays all disciplines in the database instead of filtering according to the user group
- adapt the `queryset` of the many-to-many selector within the training set admin interface
- overwrite django's `get_list_filter` method to remove `ApprovedImageListFilter` for user groups
Fixes: #289
Fixes: #290
Fixes: #192
> Bug/training set filter, fixes #290 289 #192

- README.md
- src/vocgui/urls.py
- src/vocgui/views/__init__.py
- src/vocgui/views/word_viewset.py
Add API endpoint for all default words
- Add endpoint `api/words/` to get all default words (created by admins)
Fixes: #304
> Add API endpoint for all default words

- README.md
- src/vocgui/models/discipline.py
- src/vocgui/serializers.py
This PR adds a `nested_training_set_ids` field to all `discipline` endpoints.
- add `get_nested_training_sets` method to ` discipline` model
- include `get_nested_training_sets` to `discipline` serializer
Fixes: #322
> add nested training sets to discipline serializer

- docs/src/index.rst
- tools/build_documentation.sh
Apparently, readthedocs does not find the tests module and I can't find a way around it... let's remove it for now to fix the documentation build.
- Remove tests from documentation
> Remove tests from documentation

- CHANGELOG.md
- lunes_cms/cms/models/document_image.py
makes image preview work regardless of whether the file extension is upper or lower case
- Checks the file extension against a lower case version of the file name so that the case of the file extension doesn't matter.
Fixes: #338
> image preview supports .png and .jpg regardless of extension case

- CHANGELOG.md
- lunes_cms/cms/templates/public_upload.html
As we now have many photos in our content management system, the list of missing images per training set is rather short. This makes it cumbersome to go through all disciplines and training sets to find and upload missing images.
When selecting a discipline, we now directly show associated documents. This skips the step of selecting a training set.
Fixes: [INFRA-205](https://issues.tuerantuer.org/browse/INFRA-205)
> Change public upload, fixes INFRA-205

- README.md
- docs/src/installation.rst
- docs/src/prod-server.rst
- lunes_cms/README.md
- requirements.system
- tools/install.sh
`libpq-dev` is required to compile `psycopg2` which wasn't documented.
> Add `libpq-dev` to system prerequisites

- CHANGELOG.md
- lunes_cms/cms/admins/discipline_admin.py
- lunes_cms/cms/admins/training_set_admin.py
- lunes_cms/cms/models/discipline.py
- lunes_cms/cms/models/document_image.py
- lunes_cms/cms/models/training_set.py
- lunes_cms/cms/static/js/image_preview.js
- lunes_cms/cms/utils.py
- lunes_cms/locale/de/LC_MESSAGES/django.po
Add icon preview for disciplines and training sets
- Generalize the existing preview script to make it work for both the document images and the discipline/trainingset icons
- Add image tag to discipline and training set admins
Fixes: #317
> Add icon preview for disciplines and training sets

- CHANGELOG.md
- lunes_cms/cms/views/other_viewset.py
Fix public upload
- Remove outdated name field from image creation
Fixes: #358
> Fix public upload

- lunes_cms/api/templates/swagger_ui.html
In our [new API documentation](https://lunes-test.tuerantuer.org/api/docs/), the validator badge was overwritten with our custom logo:
- Overwrite only logo in top bar, not in footer
Now, it looks like this:
> Fix validator badge in API docs

- CHANGELOG.md
- lunes_cms/help/templates/public_upload.html
- lunes_cms/help/views/public_upload.py
This PR tries to improve the filter on our public upload site
- I added a function to sort first the disciplines, this works as expected
- I used this function also to sort the documents, and this doesn't work as expected. I think l.92 is responsible for this. When I console.log the elements before l. 92 the documents are sorted as expected, when I check after l. 92 it doesn't work, and it shows the vocubularies in a semi sorted way. Do you have an idea how what the issue is here?
- I added the option to see all missing words
- I added an option to immediately access your camera on your mobile phone. However, this needs to be tested a lot, because I had different results on different devices.
Fixes: #369 
Fixes: #372
> Improve filter on public upload

- .github/dependabot.yml
Ignore dependabot updates for Django >=4.0 to prevent PRs like #382 in the future
> Ignore dependabot updates for Django >=4.0

- .github/dependabot.yml
Since we're not releasing new lunes cms versions that frequently, I guess it makes sense to also bump the dependency versions less frequently.
- Change dependabot frequency from weekly to monthly
> Change dependabot frequency from weekly to monthly

- CHANGELOG.md
- lunes_cms/api/v1/views/word_viewset.py
- tests/api/api_config.py
- tests/api/expected-results/words_170.json
- tests/api/expected-results/words_by_key.json
Add the possibility to retrieve public vocabulary words
- Extend the queryset of the `/words` endpoint when an API key is given
- Adapt tests
Fixes: #404
> Deliver protected vocabulary at `/words` API endpoint

- CHANGELOG.md
- lunes_cms/core/settings.py
- setup.cfg
Since today's release, [django-jazzmin 2.6.0](https://pypi.org/project/django-jazzmin/#history) finally supports [different logos on the login form](https://github.com/farridav/django-jazzmin/pull/397).
Before:
| Light mode | Dark mode |
|------------|-----------|
| ![Screenshot 2022-11-03 at 20-44-23 Anmelden Lunes-Verwaltung](https://user-images.githubusercontent.com/16021269/199820098-cd23ed26-678b-4d36-aec0-ecbe9d78c9b4.png) | ![Screenshot 2022-11-03 at 20-44-32 Anmelden Lunes-Verwaltung](https://user-images.githubusercontent.com/16021269/199820123-2a6c1424-6153-4c9e-8824-ca10f097ec0b.png) |
After:
| Light mode | Dark mode |
|------------|-----------|
| ![Screenshot 2022-11-03 at 20-39-56 Anmelden Lunes-Verwaltung](https://user-images.githubusercontent.com/16021269/199820160-a25e978c-2 …
> Use different logo on login form

- .github/dependabot.yml
GitHub released [grouped version updates for Dependabot in public beta](https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/) now.
This should hopefully result in only one dependabot PR per month which contains all version updates, instead of one PR per dependency.
Also see config docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
> Enable grouped version updates for dependabot

- CHANGELOG.md
- lunes_cms/cms/admin.py
- lunes_cms/cms/admins/discipline_admin.py
- lunes_cms/cms/admins/document_admin.py
- lunes_cms/cms/admins/training_set_admin.py
- lunes_cms/cms/list_filter.py
- lunes_cms/cms/templates/admin/discipline_filter.html
- lunes_cms/cms/templatetags/__init__.py
- lunes_cms/cms/templatetags/admin_filter_tags.py
- lunes_cms/locale/de/LC_MESSAGES/django.po
This adds a few improvements for the admin list filters
- Add module and vocabulary counters to discipline list
- Add vocabulary counters to training set list
- Group discipline filter by parent discipline
- Limit training set filter options by selected discipline and vice versa
- Add possibility to filter vocabulary with no approved images
- Add possibility to filter vocabulary by released training sets
Fixes: #368
Fixes: #476
> Improve admin list filters

- .pylintrc
- lunes_cms/api/v1/serializers/discipline_serializer.py
- lunes_cms/api/v1/serializers/feedback_serializer.py
- lunes_cms/api/v1/serializers/group_serializer.py
- lunes_cms/cms/admins/discipline_admin.py
- lunes_cms/cms/admins/training_set_admin.py
- lunes_cms/cms/models/document.py
- lunes_cms/cms/models/group_api_key.py
- lunes_cms/cms/utils.py
- lunes_cms/locale/de/LC_MESSAGES/django.po
This PR enables pylint rules which are currently disabled.
- Enable `raise-missiong-from`
- Enable `empty-docstring`
- Enable `missing-function-docsring`
Fixes: (#499, partially)
> Enable pylint rules 1

- CHANGELOG.md
- lunes_cms/cms/admins/feedback_admin.py
- lunes_cms/cms/feedback_filter.py
- lunes_cms/cms/fixtures/test_data.json
- lunes_cms/cms/templates/admin/base.html
- lunes_cms/core/context_processors.py
- lunes_cms/locale/de/LC_MESSAGES/django.po
This PR changes the feedback view so admin users see all the feedback entries but non_admin users only feedback entries related to the objects they created.
- add a new query to exclude feedback entries that are not related to the user, if they are not admin.
Fixes: #353
> Filter feedback by object creator

- CHANGELOG.md
- lunes_cms/cms/admins/document_admin.py
- lunes_cms/locale/de/LC_MESSAGES/django.po
Fix the problem that input fields are squashed when an user is working on a small screen.
So far as I tested this (or a similar) problem was not found in other parts of the system.
- Do not list more than one input field in one row.
Fixes: #534
> Adjust form appearance for small screens

- CHANGELOG.md
- lunes_cms/api/utils.py
- lunes_cms/api/v1/urls.py
- lunes_cms/cms/fixtures/test_data.json
- lunes_cms/locale/de/LC_MESSAGES/django.po
- lunes_cms/static/js/toggle_plural_field.js
- tests/api/api_config.py
- tests/api/expected-results/duplicate_Ei.json
- tests/api/expected-results/duplicate_Schere.json
- tests/api/expected-results/duplicate_implementieren.json
- tests/api/expected-results/duplicate_neueswort.json
This PR adds a functionality that informs user of possible duplication when they are editing/creating a word.
- Introduce a new function <s>`get_documents_by_string`</s> `find_duplicates_for_word`, which looks for documents objects with the same "word" attribute.
- Call it whenever something is changed in the `word` field on the document form
- Show users whether the current input has a duplicate in the system or not.
Fixes: #470
> Inform users of word duplication in document form

- CHANGELOG.md
- lunes_cms/static/css/feedback.css
This PR fixes the color conflict, which is a side effect of #515 
- Introduce a new color assignment to feedback list in the dark mode
🤔 The contrast between "bold" and "normal" fonts is sadly not really visible enough in the dark mode (I can only slightly tell whether bold or normal). Should we use different font colors depend on the status (read/unread)? @hauf-toni 
This is how it looks after fix with this PR.
Fixes: #532
> Fix colors of feedback list in dark mode

- .circleci/config.yml
Since https://github.com/digitalfabrik/lunes-cms/pull/522 is merged the `develop` CircleCI workflow on the `develop` branch fails: https://app.circleci.com/pipelines/github/digitalfabrik/lunes-cms/892/workflows/ff6e4038-dc60-47be-9fdc-7d5f58ccdf9f
Somehow the name of the `tar.gz` file changed from `./dist/lunes-cms-*.tar.gz` to `./dist/lunes_cms-*.tar.gz`.
To find the bug I've listed the files in the workspace: https://app.circleci.com/pipelines/github/digitalfabrik/lunes-cms/936/workflows/01bf749a-3bfa-4a68-af92-588ca6d32c16/jobs/7422
Changed the file name pattern in the `publish-package` step.
> CircleCI: Fix `publish-package` step
