src/vocgui/static/scripts.js

Verify almost correct user input by calculating its Levenshtein distance to the target word.
* solves #5 
* Levenshtein function ("getEditDistance") calculates the distance between two strings: for every wrong character, the distance grows by 1.
* User input is verified as "almost correct" for Levenshtein distance of 1.

Improve and extend fuzzymatch

---

src/vocgui/static/scripts.js

Height of images was fixed at 350px
- Small changes of render_question() and render_question_solved(): The img element of the html string was adapted. The style attribute "height" now equals 350px
- All images now have the same height, regardless of the image's size
- Goal: Adapt the height of the image with reference to the screen size //solved

Standardize Image Sizes, solves #10

---

src/vocgui/static/scripts.js

When hitting the "Solve" button, all alternative solutions are shown.
- function solve_document is extended and modifies the html appearance.
- All alternative solutions are shown under the "Next Word" button.

Show all alternative words when solving, solves #19

---

src/vocgui/static/manifest.json
src/vocgui/static/scripts.js

With this, the PWA finally works in Chrome.
Co-authored-by: Mael Fosso <fosso@integreat-app.de>
Co-authored-by: Emmanuel Kembou <e.kembou@live.de>

Fix PWA ServiceWorker and manifest

---

src/vocgui/admin.py
src/vocgui/models.py

Adapted the `admin.py` 
- so the foreignKey fields have a search bar for assigning values instead of just a drop-down menu
- so there is a search bar on top of each model page

Improve foreignKey assignment, fixes #47

---

setup.py
src/vocgui/admin.py
src/voctrainer/settings.py

**Minor Bugs**
- removed old swagger package from dependencies
- switched sorting order within training sets lists

fix minor issues

---

src/vocgui/list_filter.py

used ugettext_lazy instead of ugettext in list_filter.py

bugfix translation of filter name

---

src/vocgui/models.py

lunes wording change: replaced article "Nomen" by "Substantiv"

changed article "Nomen" to "Substantiv"

---

src/vocgui/models.py

- Change return string of document image module

fix dunder str of document image

---

README.md
src/vocgui/views.py

**Summary:**
Restricted all requests except `GET` requests
**Proposed Changes:**
- Adapted `views.py`: added `http_method_names = ['get']` to every viewset
- along the way I adapted the `README.md`

remove put, post, patch and delete requests fixes #126

---

src/vocgui/forms.py

Added alphabetical ordering to unchosen vocabulary/disciplines for widgets in trainingset creation by modifying the querysets with order_by()

[MVP -> master branch] Feature/ordered trainingset widgets

---

src/vocgui/models.py

* Add a static default_group_name
* Skip adding a default group if no group exists. This
enables using the createsuperuser subcommand.
Fixes #164

Change default group handling

---

src/vocgui/templates/public_upload.html
src/vocgui/views.py

* Require checkbox.
* Show success message.
@lukasboehm97 I was already finished, therefore created a commit. You can choose if you like your implementation more :)
Conflicts with commit eb3327816f784ead577dcb8da44999b69a79e5d2 of #184.

Improve public upload

---

src/vocgui/templates/public_upload.html

* Allow uploading images from smartphone storage by making camera optional.

Upload: change upload template

---

src/vocgui/templates/public_upload.html

Make manual for creating photos more visible.

Change public upload form layout

---

src/vocgui/templates/public_upload.html
src/vocgui/views/other_viewset.py

Add disciplines drop down to public upload form and a filter function for training sets, depending on the selected discipline.

Add disciplines to public upload

---

src/vocgui/models/group_api_key.py

Fix api key length (prefix=3, secret=7)

fix api length

---

src/vocgui/admins/document_admin.py

Fix sorting documents by image
- Annotate queryset of documents with three additional attributes:
- `has_image` is `True` if the document has at least one image
- `has_confirmed_image` is `True` if the document has at least one confirmed image
- `image_sort` is `2`, it if has at least one confirmed image, `1` if it has at least one image and `0` if it does not have any image
- Perform ordering by `image_sort` instead of `document_image` (which led to duplicated entries)
Fixes: #296

Fix sorting documents by image

---

src/vocgui/admins/document_admin.py
src/vocgui/models/document_image.py
src/vocgui/static/js/image_preview.js

Add image preview before upload
- Show a preview after a file has been selected for upload
- Remove file preview if deletion-checkbox is clicked
Fixes: #315

Add image preview before upload

---

src/vocgui/serializers.py
src/vocgui/static/images/fallback-icon.svg

Add fallback icon for disciplines and trainingsets
Fixes: #308

Add fallback icon for disciplines and trainingsets

---

README.md
src/vocgui/urls.py
src/vocgui/views/discipline_viewset.py

Improve disciplines API endpoint
- Return all disciplines, not only leaf nodes
- Filter by API key instead of given group id
- Enable detail view to get single records
Fixes: #307

Improve disciplines API endpoint

---

src/vocgui/urls.py
src/vocgui/views/__init__.py
src/vocgui/views/training_set_by_id_viewset.py

An endpoint was added to get details of a training-set by providing the training-set id
Added "training_set_details" endpoint
Added training-set-by-id viewset

endpoint for training_set details

---

.circleci/config.yml

The develop workflow is not needed on the main branch.
- Skip the develop workflow on the main branch

Skip develop workflow on main branch

---

.circleci/config.yml
CHANGELOG.md
docs/src/index.rst
lunes_cms/cms/models/document_image.py
lunes_cms/cms/templates/public_upload.html
tools/build_documentation.sh

* [ [#338](https://github.com/digitalfabrik/lunes-cms/issues/338) ] Support image preview regardless of extension case
* [ [#343](https://github.com/digitalfabrik/lunes-cms/issues/343) ] Remove module dropdown in public upload

Deploy public upload & preview for other image extensions

---

.readthedocs.yaml
docs/src/conf.py

Try to fix the documentation build. Unfortunately, there is no way of testing this before merging it into develop, so let's just hope it works.
- Add missing imports in sphinx config
- Remove PDF and ePub builds from documentation
This does not solve an issue, but is a precondition for #277

Fix documentation build

---

.github/CODEOWNERS
.readthedocs.yaml
CHANGELOG.md
docs/src/conf.py
lunes_cms/cms/views/other_viewset.py

Release the bugfix for the public upload 
* [ [#358](https://github.com/digitalfabrik/lunes-cms/issues/358) ] Fix public image upload

Release 2022.6.2

---

.github/dependabot.yml
CHANGELOG.md
lunes_cms/api/v1/views/word_viewset.py
lunes_cms/core/settings.py
setup.cfg
tests/api/api_config.py
tests/api/expected-results/words_170.json
tests/api/expected-results/words_by_key.json

Once #405 is merged, we should directly release the fix.
* [ [#404](https://github.com/digitalfabrik/lunes-cms/issues/404) ] Deliver protected vocabulary words in API

Release `2022.10.0`

---

CHANGELOG.md
lunes_cms/static/css/corporate_identity.css

Fix background color in dark mode
- Fix background color of `.content-wrapper`
- Fix background color of `.main-footer`
Fixes: #418

Fix background color in dark mode

---

CHANGELOG.md
README.md
lunes_cms/static/css/corporate_identity.css
setup.cfg

Release the bugfix for dark mode
* [ [#418](https://github.com/digitalfabrik/lunes-cms/issues/418) ] Fix background color in dark mode

Release `2022.12.0`

---

docs/src/conf.py
setup.cfg

I merged the changes of my fork back into the original package

Move from `sphinxcontrib-django2` to `sphinxcontrib-django`

---

README.md

This PR updates the README file, and changes the contributor from Digital Factory to Digitalfabrik
- Update Digital Factory to Digitalfabrik in README
Fixes: -

Update readme from Digital Factory to Digitalfabrik

---

LICENSE
NOTICE.md
README.md
setup.cfg

Clarify copyright notice
- Fill in template `Copyright [yyyy] [name of copyright owner]` 
- Move copyright notice to own file `NOTICE` as suggested [here](https://apache.org/foundation/license-faq.html#Apply-My-Software)

Clarify copyright notice

---

CHANGELOG.md
lunes_cms/cms/admins/document_admin.py
lunes_cms/locale/de/LC_MESSAGES/django.po

This PR adds professions related to each word in the vocabulary overview
- Add related professions in the vocabulary overview
Fixes: #267

Add professions in the vocabulary overview

---

CHANGELOG.md
lunes_cms/cms/admins/feedback_admin.py
lunes_cms/static/css/feedback.css
lunes_cms/static/js/color_unread_feedback.js

This PR highlights unread feedback entries in the list.
- Make letters bold in unread feedback entries by Javascript
Fixes: #352

Highlight unread feedback

---

lunes_cms/cms/admins/document_admin.py
lunes_cms/locale/de/LC_MESSAGES/django.po

It seems I have overlooked something in the review or messed up while rebasing, the changes from #510 are not effecting in the develop branch 🙈 🙇 
- Add them to `fields` of `DocumentAdmin` and revive them 
Fixes: #

revive definition and additional fields

---

lunes_cms/api/v1/serializers/alternative_word_serializer.py
lunes_cms/api/v1/serializers/document_serializer.py
tests/api/expected-results/documents_by_training_set_108.json
tests/api/expected-results/documents_by_training_set_7.json
tests/api/expected-results/words.json
tests/api/expected-results/words_170.json
tests/api/expected-results/words_2.json
tests/api/expected-results/words_by_key.json

This PR makes the CMS API compatible with App.
-
-
-
Fixes: #

Revive API and APP

---

lunes_cms/api/v1/serializers/alternative_word_serializer.py
lunes_cms/api/v1/serializers/document_serializer.py
tests/api/expected-results/documents_by_training_set_108.json
tests/api/expected-results/documents_by_training_set_7.json
tests/api/expected-results/words.json
tests/api/expected-results/words_170.json
tests/api/expected-results/words_2.json
tests/api/expected-results/words_by_key.json

- Make the API compatible with the App after I have broken it
-
-
Fixes: #

Release `2024.5.1`

---

CHANGELOG.md
lunes_cms/api/utils.py
lunes_cms/api/v1/urls.py
lunes_cms/cms/admins/discipline_admin.py
lunes_cms/cms/admins/document_admin.py
lunes_cms/cms/admins/document_resource.py
lunes_cms/cms/admins/feedback_admin.py
lunes_cms/cms/feedback_filter.py
lunes_cms/cms/fixtures/test_data.json
lunes_cms/cms/templates/admin/base.html
lunes_cms/core/context_processors.py
lunes_cms/core/settings.py
lunes_cms/locale/de/LC_MESSAGES/django.po
lunes_cms/static/js/toggle_plural_field.js
setup.cfg
tests/api/api_config.py
tests/api/expected-results/duplicate_Ei.json
tests/api/expected-results/duplicate_Schere.json
tests/api/expected-results/duplicate_implementieren.json
tests/api/expected-results/duplicate_neueswort.json

- [ [#353](https://github.com/digitalfabrik/lunes-cms/issues/353) ] Filter feedback by creator of related objects
- [ [#468](https://github.com/digitalfabrik/lunes-cms/issues/468) ] Excel list out of existing vocabulary in cms
- [ [#534](https://github.com/digitalfabrik/lunes-cms/issues/534) ] Adjust form appearance for small screens
- [ [#470](https://github.com/digitalfabrik/lunes-cms/issues/470) ] Inform users of word duplication in document form

Release `2024.6.0`

---

CHANGELOG.md
lunes_cms/locale/de/LC_MESSAGES/django.po

Change language into gender neutral language
- Change words into gender neutral language
Fixes: #512

Change language to gender neutral language

---

docs/src/conf.py
setup.cfg

Preparation for releasing version `2024.7.0`

Prepare release `2024.11.0`
